sudo: required

language: ruby

matrix:
  include:
    - os: linux
      compiler: gcc      

install :
  
  - g++ --version

  - mkdir lemon-build
  - cd lemon-build
  - wget http://lemon.cs.elte.hu/pub/sources/lemon-1.3.1.tar.gz
  - tar -xvzf lemon-1.3.1.tar.gz
  - cd lemon-1.3.1
  
  # comment out error causing line in build
  - sed -i '3s/^/#/' CMakeLists.txt
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../../../

before_script:
 - gem install rake-compiler rake

script:
  - rake compile
  - rake test